#!/usr/local/bin/bash
#: Description : print formatted sales report

## Build a long string of equal signs
divider=====================================
divider=$divider$divider

## format strings for printf
header="\n %-10s %11s %8s %10s\n"
format=" %-10s %11.2f %8d %10.2f\n"

## width of divider
totalwidth=44

## print categories
printf "$header" ITEM "PER UNIT" NUM TOTAL

## print divider to match width of report
printf "%$totalwidth.${totalwidth}s\n" "$divider"

## print lines of report
printf "$format" \
	Chair 79.95 4 319.8 \
	Table 200.99 1 209.99 \
	Armchair 315.49 2 630.98
