#!/usr/local/bin/bash
#: Title			: hwcreator
#: Date 			: 2014-02-16
#: Author			: "Afiq Johari"
#: Version			: 1.0
#: Description		: create hw script in $HOME/bpl/bin/
#:		          	  ,make it executable, and execute it
#: Options 			: None

echo printf \"%s\\\n\" \"Hello, World!\" > $HOME/bpl/bin/hw
chmod +x $HOME/bpl/bin/hw
$HOME/bpl/bin/hw
